version: "3.7"
services:
  warehouse:
    build: .
    image: springio/warehouse
    ports:
      - "8081:8081"
    container_name: warehouse
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/test_user
      - SPRING_DATASOURCE_USERNAME=test_user
      - SPRING_DATASOURCE_PASSWORD=test_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: postgres:13.1-alpine
    container_name: db
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
    expose:
      - 5432
